routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// homepage
Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('home', [DashboardController::class, 'index'])->name('home');
    Route::resource('transactions', TransactionController::class);
});

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Models\OrderHistory;
use App\Models\TopupHistory;
use App\Models\Transaction;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Yajra\DataTables\Facades\DataTables;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        // Get user id
        $userid = Auth::user()->id;

        $query = Transaction::with(['topupHistory', 'orderHistory'])
            ->where('user_id', $userid)
            ->reorder('updated_at', 'desc')->get();

        return view('pages.transactions.index', compact('query'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('pages.transactions.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        // Validate the request
        $validated = $request->validate([
            'type' => 'required|in:topup,order',
            'add' => 'required|numeric',
            'description' => 'required',
            'image' => 'nullable|image|max:2048' // Maximum image size is 2MB
        ]);

        // Get user id
        $userid = Auth::user()->id;

        // If 'type' is 'topup' and 'image' is provided, handle the image upload
        if ($validated['type'] === 'topup' && $request->hasFile('image')) {
            $imagePath = $request->file('image')->store('images/topup', 'public');
        }

        // Calculate the 'final' value based on the 'current' value of the latest transaction from current user
        $latestTransaction = Transaction::where('user_id', $userid)
            ->latest('created_at')->first();
        $current = $latestTransaction ? $latestTransaction->final : 0;

        // Adjust the 'add' amount based on the transaction type (subtract for 'order' type)
        $add = $validated['add'];
        if ($validated['type'] === 'order') {
            $add *= -1; // Multiply by -1 to subtract the value
        }

        $final = $current + $add;

        // Create a new transaction with the validated data
        $transaction = new Transaction([
            'user_id' => $userid,
            'type' => $validated['type'],
            'current' => $current,
            'add' => $add,
            'final' => $final,
        ]);

        // Generate a unique ref_id based on the transaction type
        $ref_id_prefix = $validated['type'] === 'topup' ? 'T' : 'O';
        $uniqueid = strtoupper(Str::random(6));
        $ref_id = $ref_id_prefix . $uniqueid;

        // Save the transaction record to the database
        $transaction->ref_id = $ref_id; // Assign ref_id to the generated unique ID
        $transaction->save();

        // Check if 'type' is 'topup'. If yes, create a topup history record.
        if ($validated['type'] === 'topup') {
            $topupHistory = new TopupHistory([
                'amount' => $validated['add'],
                'description' => $request['description'],
                'transaction_id' => $transaction->id,
                'image_path' => $imagePath ?? null // Save the image path if it exists
            ]);
            $topupHistory->save(); // Save the record to the database
        }

        // Check if 'type' is 'order'. If yes, create an order history record.
        if ($validated['type'] === 'order') {
            $orderHistory = new OrderHistory([
                'amount' => $validated['add'],
                'description' => $request['description'],
                'transaction_id' => $transaction->id
            ]);
            $orderHistory->save(); // Save the record to the database
        }

        if ($request->has('save_only')) {
            // code to back and save
            return back()->with('success', 'Transaction added Succesfully!');
        } elseif ($request->has('save_and_back')) {
            // code to exit and save
            return redirect()->route('transactions.index')->with('success', 'Transaction added Succesfully!');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        // Find the transaction with the given ID
        $transaction = Transaction::with(['user'])->findOrFail($id);

        // Check if 'type' is 'topup'. If yes, get topup history record.
        if ($transaction->type === 'topup') {
            $history = $transaction->topupHistory;
        }

        // Check if 'type' is 'order'. If yes, get order history record.
        if ($transaction->type === 'order') {
            $history = $transaction->orderHistory;
        }

        // Return the transaction and history to the view
        return view('pages.transactions.show', compact('transaction', 'history'));
    }


    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/pages/transactions/create.blade.php
@extends('layouts.sb')

@section('heading')
    Transactions
@endsection

@section('content')
    {{-- notification --}}
    @include('components/flash-messages')
    {{-- end notification --}}

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="row">
        <div class="col-md-12">
            <div class="card border-left-primary shadow">

                <div class="card-header">
                    Add new Transactions
                </div>

                <div class="card-body">
                    <form action="{{ route('transactions.store') }}" method="post" enctype="multipart/form-data">
                        @csrf

                        <!-- Create row then inside there are 2 col md 6 -->
                        <!-- Type & Amount -->
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="type" class="form-control-label">Type</label>
                                    <select name="type" id="type" class="form-control" required>
                                        <option value="" disabled selected>-- Select Type --</option>
                                        <option value="topup">Topup</option>
                                        <option value="order">Order</option>
                                    </select>
                                    @error('type')
                                        <div class="text-muted">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="add" class="form-control-label">Amount</label>
                                    <input type="number" class="form-control" name="add" id=""
                                        value="{{ old('add') }}" required>
                                    @error('add')
                                        <div class="text-muted">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="description" class="form-control-label">Description</label>
                                    <input type="text" class="form-control" name="description" id=""
                                        value="{{ old('description') }}" required>
                                    @error('description')
                                        <div class="text-muted">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                             <!-- Add file input for image -->
                             <div class="col-md-12">
                                <div class="form-group" style="display: none">
                                    <label for="image" class="form-control-label">Image</label>
                                    <input type="file" class="form-control" name="image" id="image">
                                    @error('image')
                                        <div class="text-muted">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <button type="submit" name="save_only" class="btn btn-primary">Save</button>
                            <button type="submit" name="save_and_back" class="btn btn-info">Save and Back</button>
                        </div>

                    </form>
                </div>


            </div>
        </div>
    </div>
@endsection

@push('addon-script')
    <script>
        document.getElementById('type').addEventListener('change', function() {
            var addInput = document.querySelector('input[name="add"]');
            var descriptionInput = document.querySelector('input[name="description"]');
            var imageInput = document.querySelector('input[name="image"]');
            var type = this.value;

            // Hide the image input if the type is 'order', else show it
            if (type === 'order') {
                imageInput.closest('.form-group').style.display = 'none';
                addInput.required = true;
                descriptionInput.required = true;
            } else {
                imageInput.closest('.form-group').style.display = 'block';
                addInput.required = false;
                descriptionInput.required = false;
            }
        });
    </script>
@endpush

resources/views/pages/transactions/index.blade.php
@extends('layouts.sb')

@section('heading')
    Transactions
@endsection

@section('content')
    {{-- notification --}}
    @include('components/flash-messages')
    {{-- end notification --}}

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="row">
        <div class="col-md-12">
            <a href="{{ route('transactions.create') }}" class="btn btn-primary mb-3">
                Create Transaction
            </a>
        </div>

        <div class="col-md-12">
            <div class="card shadow">

                <div class="card-header">
                    <h6 class="m-0 font-weight-bold text-primary">Transactions</h6>
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover scroll-horizontal-vertical" id="crudTable"
                            width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th class="d-none">Id</th>
                                    <th>Trx Code</th>
                                    <th>Type</th>
                                    <th>Desc</th>
                                    <th>Current balance</th>
                                    <th>Amount</th>
                                    <th>Final Balance</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($query as $item)
                                    <tr>
                                        <td class="d-none">{{ $item->id }}</td>
                                        <td>{{ $item->ref_id }}</td>
                                        <td>{{ $item->type }}</td>
                                        @if ($item->type == 'topup')
                                            <td>{{ $item->topupHistory->description }}</td>
                                        @else
                                            <td>{{ $item->orderHistory->description }}</td>
                                        @endif
                                        <td>{{ $item->current }}</td>
                                        <td>{{ $item->add }}</td>
                                        <td>{{ $item->final }}</td>
                                        <td>
                                            <a class="btn btn-info" href="{{ route('transactions.show', $item->id) }}">
                                                Detail
                                            </a>
                                        </td>
                                    </tr>
                                @empty
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>


            </div>
        </div>
    </div>
@endsection

@push('addon-script')
    <script>
        // AJAX DataTable
        var datatable = $('#crudTable').DataTable({
            dom: 'Bfrtip',
            buttons: [{
                extend: 'excelHtml5',
                title: 'transaction_export',
                filename: 'transaction_export',
                exportOptions: {
                    columns: [1, 2, 3, 4, 5, 6] // Exclude columns 0 (Id) and 7 (Action)
                },
            }, ],
            paging: true,
            pageLength: 10,
            order: [[ 0, "desc" ]]
        });
    </script>
@endpush

resources/views/pages/transactions/show.blade.php
@extends('layouts.sb')

@section('heading')
    Details Transaction
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Transaction Details</div>

                    <div class="card-body">
                        <div class="form-group row">
                            <label for="ref_id" class="col-md-4 col-form-label text-md-right">Transaction ID</label>
                            <div class="col-md-6">
                                <input id="ref_id" type="text" class="form-control" name="ref_id"
                                    value="{{ $transaction->ref_id }}" readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="username" class="col-md-4 col-form-label text-md-right">Username / email</label>
                            <div class="col-md-6">
                                <input id="username" type="text" class="form-control" name="username"
                                    value="{{ $transaction->user->name }} / {{ $transaction->user->email }}" readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="type" class="col-md-4 col-form-label text-md-right">Type</label>
                            <div class="col-md-6">
                                <input id="type" type="text" class="form-control" name="type"
                                    value="{{ $transaction->type }}" readonly>
                            </div>
                        </div>

                        @if (isset($history))
                            <div class="form-group row">
                                <label for="amount" class="col-md-4 col-form-label text-md-right">Amount</label>
                                <div class="col-md-6">
                                    <input id="amount" type="text" class="form-control" name="amount"
                                        value="{{ $history->amount }}" readonly>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>
                                <div class="col-md-6">
                                    <input id="description" type="text" class="form-control" name="description"
                                        value="{{ $history->description }}" readonly>
                                </div>
                            </div>

                            @if ($transaction->type == 'topup')
                                <div class="form-group row">
                                    <label for="description" class="col-md-4 col-form-label text-md-right">Proof
                                        Image</label>
                                    <div class="col-md-6">
                                        <img src="{{ asset('storage/' . $history->image_path) }}" alt="Transaction Image"
                                            class="img-fluid">

                                    </div>
                                </div>
                            @else
                            @endif
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection